### ISSUE TITLE
Tweak to Forms/Light/Form Text Area

### ISSUE THREAD

**Issue by agmilmoe** [PredixDev/px-design-stencils#10]
Consider changing State/Text/Format/Input text style setting from Alignment "Auto" to "Fixed" so that multiple lines of input text will wrap inside the text box. (Instead of running on as a single line that gets truncated.)

I changed this setting and got the desired result, but have not extensively tested this modification.

Thanks!

**Comment by waifong** [comment]
Moving to new repo
