### ISSUE TITLE
Stencil is looking for SFUIText

### ISSUE THREAD

**Issue by skistz** [PredixDev/px-design-stencils#7]
Stencil is looking for SFUIText Medium, Regular and Semibold. It's not needed and might be an artifact.

![image](https://user-images.githubusercontent.com/25310251/28885259-18e95920-776a-11e7-92c0-df3182156026.png)

**Comment by waifong** [comment]
Fixed Mobile fonts in new repo

**Comment by waifong** [comment]
Fixed Mobile fonts in new repo
